//! 符号命令映射，将 `\alpha` / `\leq` 等命令转换为对应 Unicode 字符

use phf::phf_map;

static SYMBOLS: phf::Map<&'static str, &'static str> = phf_map! {
    // Greek lowercase
    "alpha" => "α",
    "beta" => "β",
    "gamma" => "γ",
    "delta" => "δ",
    "epsilon" => "ε",
    "varepsilon" => "ϵ",
    "zeta" => "ζ",
    "eta" => "η",
    "theta" => "θ",
    "vartheta" => "ϑ",
    "iota" => "ι",
    "kappa" => "κ",
    "lambda" => "λ",
    "mu" => "μ",
    "nu" => "ν",
    "xi" => "ξ",
    "omicron" => "ο",
    "pi" => "π",
    "varpi" => "ϖ",
    "rho" => "ρ",
    "varrho" => "ϱ",
    "sigma" => "σ",
    "varsigma" => "ς",
    "tau" => "τ",
    "upsilon" => "υ",
    "phi" => "φ",
    "varphi" => "ϕ",
    "chi" => "χ",
    "psi" => "ψ",
    "omega" => "ω",
    // Greek uppercase
    "Gamma" => "Γ",
    "Delta" => "Δ",
    "Theta" => "Θ",
    "Lambda" => "Λ",
    "Xi" => "Ξ",
    "Pi" => "Π",
    "Sigma" => "Σ",
    "Upsilon" => "Υ",
    "Phi" => "Φ",
    "Psi" => "Ψ",
    "Omega" => "Ω",
    // Operations
    "times" => "×",
    "div" => "÷",
    "cdot" => "·",
    "pm" => "±",
    "mp" => "∓",
    "ast" => "∗",
    "star" => "⋆",
    "dagger" => "†",
    "ddagger" => "‡",
    "circ" => "∘",
    "bullet" => "•",
    "oplus" => "⊕",
    "otimes" => "⊗",
    "oslash" => "⊘",
    "odot" => "⊙",
    "iint" => "∬",
    "iiint" => "∭",
    "iiiint" => "⨌",
    "oiint" => "∯",
    "oiiint" => "∰",
    "smallint" => "∫",
    // Relations
    "leq" => "≤",
    "le" => "≤",
    "geq" => "≥",
    "ge" => "≥",
    "neq" => "≠",
    "ne" => "≠",
    "approx" => "≈",
    "asymp" => "≍",
    "equiv" => "≡",
    "propto" => "∝",
    "sim" => "∼",
    "simeq" => "≃",
    "cong" => "≅",
    "ll" => "≪",
    "gg" => "≫",
    "subset" => "⊂",
    "supset" => "⊃",
    "subseteq" => "⊆",
    "supseteq" => "⊇",
    "subsetneq" => "⊊",
    "supsetneq" => "⊋",
    "in" => "∈",
    "notin" => "∉",
    "ni" => "∋",
    "owns" => "∋",
    "land" => "∧",
    "wedge" => "∧",
    "lor" => "∨",
    "vee" => "∨",
    "neg" => "¬",
    "vdash" => "⊢",
    "dashv" => "⊣",
    "models" => "⊨",
    "perp" => "⊥",
    "top" => "⊤",
    "bot" => "⊥",
    // Set/logic/misc
    "forall" => "∀",
    "exists" => "∃",
    "therefore" => "∴",
    "because" => "∵",
    "emptyset" => "∅",
    "varnothing" => "∅",
    "aleph" => "ℵ",
    "hbar" => "ℏ",
    "hslash" => "ℏ",
    "Im" => "ℑ",
    "Re" => "ℜ",
    "partial" => "∂",
    "nabla" => "∇",
    "triangle" => "△",
    "triangleleft" => "◁",
    "triangleright" => "▷",
    "diamondsuit" => "♦",
    "heartsuit" => "♥",
    "clubsuit" => "♣",
    "spadesuit" => "♠",
    "ell" => "ℓ",
    "wp" => "℘",
    "infty" => "∞",
    // Arrows
    "rightarrow" => "→",
    "to" => "→",
    "leftarrow" => "←",
    "leftrightarrow" => "↔",
    "Rightarrow" => "⇒",
    "Leftarrow" => "⇐",
    "Leftrightarrow" => "⇔",
    "mapsto" => "↦",
    "hookrightarrow" => "↪",
    "hookleftarrow" => "↩",
    "uparrow" => "↑",
    "downarrow" => "↓",
    "updownarrow" => "↕",
    "Uparrow" => "⇑",
    "Downarrow" => "⇓",
    "Updownarrow" => "⇕",
    // Dots
    "cdots" => "⋯",
    "ldots" => "…",
    "vdots" => "⋮",
    "ddots" => "⋱",
};

pub fn map_symbol(command: &str) -> Option<&'static str> {
    SYMBOLS.get(command).copied()
}
